name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 23 11 * * */14

jobs:
  python:
    name: Testing HugoPhotoSwipe
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        py: [ '3.8', '3.11' ] # minimal and latest
    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install libgirepository
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libgirepository1.0-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test_direct
